POST http://localhost:8080/product
Content-Type: application/json

{
    "name": "tủ lạnh",
    "description": "tủ lạnh",
    "technicalInfo": "[{\"key\":\"2\",\"value\":\"2\"}]",
    "productInfo": "<p>tét</p>",
    "price": 12,
    "discount": 1,
    "quantity": 1,
    "brandId": 2,
    "categoryId": 5,
    "images": [
        "http://localhost:8080/public/images/07f83268f431987298014f5df467aea6b118d368_14f404e5-3044-4736-a3d3-c785d359c0d7.jfif",
        "http://localhost:8080/public/images/7c978d064f8cdee94219c8a8b26acf2082356454_eda58ef1-926a-4ef0-aa19-3a9c887730c5.jfif"
    ]
}

###

DELETE http://localhost:8080/product/1
Content-Type: application/json

###
GET http://localhost:8080/product
Content-Type: application/json


